### ISSUE TITLE
Travis build sometimes fails

### ISSUE THREAD

**Issue by radka-j** [alan-turing-institute/dodo#85]
The issue are PyDodo integration tests. On some builds they all return 500 internal server error. This seems to suggest BlueSky might not be running and it is unclear why.

Is it possible asynchronous functions (the first integration tests to run) make BlueSky crash?

**Comment by radka-j** [comment]
I added a test to check BlueSky is responding before the integration tests are run. 
- The BlueSky response test passed and subsequent integration tests failed. 
- This did not happen when I commented out tests of the asynchronous and batch functions.

**Comment by radka-j** [comment]
It is possible that this might have to do with Docker resources (maybe similar reasons to why BlueSky crashed during the away day?).

For now will set up to skip these tests in Travis.

**Comment by rkm** [comment]
I had a quick look at the build log but couldn't spot anything obvious. It may have something to do with how/when the dependency containers are created though since the problem seems to be intermittent. I doubt this is to do with Docker resources, although that's something we could add monitoring for. We use the [pytest-docker-compose](https://pypi.org/project/pytest-docker-compose/) plugin in BlueBird, which makes sure that each integration test gets a fresh copy of the required containers prior to it being run, so it might be an idea to look into this for Dodo :)
